### ISSUE TITLE
功能太少

### ISSUE THREAD

**Issue by myml** [rekols/monitor-desktop#1]
CPU,内存，负载，网速，磁盘，显卡，电量，可以自己选择显示哪些。我是想这样做的。不太写c++，只能慢慢来了

**Comment by myml** [comment]
还有双击启动深度资源监视器，这个用qml没法实现

**Comment by rekols** [comment]
这样啊，没用过qml，刚刚修复了一个cpu占用过大问题。

QTime reachTime = QTime::currentTime().addMSecs(msec);

while (QTime::currentTime() < reachTime) {
    QCoreApplication::processEvents(QEventLoop::AllEvents, 100);
}

上面延迟的方法真占用CPU。

**Comment by myml** [comment]
为什么坚持QtWidgets呢，小程序用qml很方便啊，c++代码看着就麻烦

**Comment by rekols** [comment]
因为linux显卡驱动不完善，使用QML需要良好的显卡支持。

**Comment by rekols** [comment]
> 移动端设备程序开发推荐使用QT quick、QT QML，方便简单快速。
> 系统桌面端程序开饭推荐使用QT Widget，成熟高效、
> 如果仅仅用于开发交互演示程序或者用于快速开发，推荐还是用QT quick、QT QML开发，当然，你需要有一定的界面设计功底和JavaScript、HTML、CSS等语言功底。

**Comment by myml** [comment]
然而你的程序cpu占用过大...

**Comment by myml** [comment]
又不是写3D程序，也不是要做炫酷动画...

**Comment by rekols** [comment]
我修复了cpu占用过大问题。

**Comment by rekols** [comment]
还有一点不喜欢qml的语法，不知道为什么，我还是熟悉C/C++语法，哈哈哈。

**Comment by myml** [comment]
好啊，明天我试试QtWidgets，学习学习

**Comment by rekols** [comment]
okay.

**Comment by myml** [comment]
我放弃了，写C++代码让我很苦闷。用QML我能一下午完成所有功能的开发，而用widgets只完成了一个功能。我承认widgets性能比qml要高出不少，就咱两个的程序做对比，内存多了两倍，CPU多了0.1。但我的时间和快乐缺减少了

**Comment by rekols** [comment]
我静静的玩widgets...

**Comment by rekols** [comment]
都有各自的优点。。

**Comment by myml** [comment]
恩，同意
